Print better error messages

diff --git a/sshlatex b/sshlatex
--- a/sshlatex
+++ b/sshlatex
@@ -223,7 +223,7 @@ if($ARGV[1] eq "OUTPUT") {
     open my $fh, ">", $file or die $!;
 
     # We don't deactivate output buffering, since the PDF file can anyway only
-    # be viewed when it's fully transmitted.
+    # be viewed when it has been fully transmitted.
 
     while(1) {
         # Read a chunk. Stop if EOF is reached.
@@ -254,6 +254,16 @@ export LC_FILE="`basename -- "$2" .tex`"
     exit 1
 }
 
+# If sshlatex is called with a LaTeX source file which is not contained in the
+# current working directory, make sure we don't accidentally operate on an
+# unrelated file with the same basename.
+[ -e "$2" -a ! \( -e "$LC_FILE.tex" -a "$LC_FILE.tex" -ef "$2" \) ] && {
+    echo "*** Error: LaTeX source file not found. \"$LC_FILE.tex\"" >&2
+    echo "    sshlatex has to be called from the directory the source file lives in." >&2
+    exit 1
+}
+
+# Here the most probable cause is a typo.
 [ -e "$LC_FILE.tex" ] || {
     echo "*** Error: LaTeX source file not found. \"$LC_FILE.tex\"" >&2
     exit 1
@@ -420,19 +430,22 @@ EOF
         ' >&2
     ) | perl -we "$LC_EEKCAT" -- "$LC_FILE.new.pdf" INPUT || exit
 
-    if [ "${PIPESTATUS[-2]}" = "0" ]; then
-        mv -- "$LC_FILE.new.pdf" "$LC_FILE.pdf" 2>/dev/null
-    else
-        echo "*** An error occured." >&2
-    fi
+    error_occured="${PIPESTATUS[-2]}"
 
     time_of_remote_files="`cat -- "$LC_FILE.time"`"
 
     echo -n "*** Total elapsed time:     " >&2
-    perl -we "printf '%.2f seconds', $(date +%s.%N) - $time_of_remote_files" >&2
+    perl -we "printf '%.2f seconds' . $/, $(date +%s.%N) - $time_of_remote_files" >&2
+
+    if [ "$error_occured" = "0" ]; then
+        mv -- "$LC_FILE.new.pdf" "$LC_FILE.pdf" 2>/dev/null
+        beepy &>/dev/null &
+    else
+        echo "*** An error occured, local PDF file not updated." >&2
+        beepy 1 &>/dev/null &
+    fi
+
     echo >&2
-    echo >&2
-    beepy &>/dev/null &
 
     rm -- "$LC_FILE.time" 2>/dev/null
     # is used to trigger un-withholding of pdflatex log output, so has to be reset
